name = "be-studious"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "be-studious"
database_id = "1cec54f7-07ce-4a77-aa98-d4262dda1479"
preview_database_id = "DB"
